# Generated by Django 3.1.7 on 2021-05-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mymedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='Songs/')),
                ('rating', models.CharField(max_length=100)),
                ('views', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='umedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='Media/')),
                ('rating', models.CharField(max_length=100)),
                ('views', models.CharField(max_length=100)),
            ],
        ),
    ]
